#!/usr/bin/env bash

set -euo pipefail

source .builder

mkdir -p dst/

if [[ -e src/pub/ ]]; then

  printf "Building src/pub/\n"
  cp -r -T src/pub/ dst/pub/

fi

for src in src/pub.lib.*/; do
  
  if [[ -e "$src" ]]; then

    printf "Building $src\n"
    dst="${src//./\/}"
    dst="${dst/src/dst}"
    cp -r -T "$src" "$dst"

  fi

done

for src in src/pub.*/; do

  if [[ -e "$src" ]]; then
   
   if [[ ! "$src" =~ ^src/pub.lib.*/ ]]; then

      printf "Building $src\n"
      dst="${src//./\/}"
      dst="${dst/src/dst}"
      dst="${dst%\/}"
      build "$src" "${dst##*/}" "${dst%/*}"/
      
    fi

  fi

done

printf "Done\n"

